#!/bin/bash
#--------------------------------------------
# Date:`date +%Y%m%d%H%M`
# Author:hwx763490
# Desc: hive to mysql
#------------------------------------------------
# refresh env
. /etc/profile
. ~/.bash_profile

BASE_PATH=$(
  cd $(dirname $0)
  pwd
)
echo "base_path is $BASE_PATH"

# 1.连接hive,查看表分区并追加到本地文件
beeline -e 'use mdd; show partitions tss_r2;' >"$BASE_PATH"/$(date '+%Y-%m-%d')"_board_code_partition.txt"

# 2.读取本地文件，处理成想要的格式，写入到文件中
while read table; do

$(cat "$BASE_PATH"/$(date '+%Y-%m-%d')"_board_code_partition.txt"| xargs -d '|' awk -F)

# 3.读取文件中的每一行的内容，例如读取到第一行的内容是03032MWM,则进行下一步
# 这里暂时使用变量代替
board_code="03032MWM"

# 4.按业务需求命名规则拼接表名
tb_name=${board_code}"_tss_r2"

# 5.批量生成mysql建表语句并创建表
# 定义mysql变量
mysql_user="root"
mysql_password="admin"
mysql_host="10.1.196.212"
mysql_port="3306"
db_arr="mdd"
welcome_msg="开始批量创建表！"

# 判断MYSQL是否启动,mysql没有启动则直接退出
mysql_ps=`ps -ef |grep mysql |wc -l`
mysql_listen=`netstat -an |grep LISTEN |grep $mysql_port|wc -l`

if [ \[$mysql_ps == 0 ] -o [$mysql_listen == 0] ]; then
echo "ERROR:MySQL is not running! "
exit
else
echo $welcome_msg
fi

# 连接到mysql数据库，无法连接则退出
mysql -h$mysql_host -P$mysql_port -u$mysql_user -p$mysql_password <<end
use mysql;
select host,user from user where user='root' and host='localhost';
exit
end

flag=`echo $?`

if [ $flag != "0" ]; then
echo "ERROR:Can't connect mysql server! "
exit
else
echo "MySQL connect ok! Please wait......"
mysql -u $mysql_user $db_arr << EOF 2>/dev/null
"create table $tb_name(
    id int(11) NOT NULL,
    board_code varchar(255) NOT NULL,
    operation_sequence  varchar(255)  NOT NULL,
    operation_sequence_sub varchar(255) NOT NULL ,
    r2_test_item_name      varchar(255) NOT NULL ,
    StartDateTime          timestamp NOT NULL ,
    StopDateTime          timestamp NOT NULL,
) DEFAULT CHARSET=utf8";
EOF
# 6.表创建好后，利用sqoop将hive分区的数据分别导出到mysql表
// 测试数据库连接
sqoop eval --connect jdbc:mysql://192.168.180.11/angel --username root--password root

// MySQL导入到Hive
sqoop import --connect jdbc:mysql://localhost:3306/test --username root --password 123456 --table person -m 1 --hive-import

// 导出该某Hive表所有数据到MySQL
sqoop export --connect jdbc:mysql://192.168.11.172:16408/ztsrm  --username srm --password handhand  --table invoice_lines  --export-dir /apps/hive/warehouse/srm.db/invoice_lines_temp2/jobid=106 --input-fields-terminated-by ','  --input-null-string "\\\\N" --input-null-non-string "\\\\N"

// 导出该某Hive表指定分区数据到MySQL
sqoop export --connect jdbc:mysql://192.168.11.172:16408/ztsrm  --username srm --password handhand  --table invoice_lines  --export-dir /apps/hive/warehouse/srm.db/invoice_lines_temp2 --input-fields-terminated-by ','  --input-null-string "\\\\N" --input-null-non-string "\\\\N"

fi
done <$(date '+%Y-%m-%d')_board_code_partition.txt
