#!/usr/bin/python
# encoding: utf-8
# -*- coding: utf8 -*-
"""
Created by PyCharm.
File:               LinuxBashShellScriptForOps:getFileLastLine.py
User:               hejun
Create Date:        2019/8/3
Create Time:        11:05
 """
import os

def get_file_last_line(inputfile):
    filesize = os.path.getsize(inputfile)
    blocksize = 1024
    with open(inputfile, 'r') as f:
        last_line = ""
        if filesize > blocksize:
            maxseekpoint = (filesize // blocksize)
            f.seek((maxseekpoint - 1) * blocksize)
        elif filesize:
            f.seek(0, 0)
        lines = f.readlines()
        if lines:
            lineno = 1
            while last_line == "":
                last_line = lines[-lineno].strip()[-11:].replace("\r|\n|", " ")
                lineno += 1
        return last_line

data = os.path.dirname(os.path.abspath(__file__))
inputfile = os.path.join(data, 'data.txt')
print(inputfile)
print(get_file_last_line(inputfile))

